description: CompSoc is Scotland's best and largest tech society. We do talks, workshops, and plenty of socials.

sass:
   sourcemap: true

url: "https://findoslice.com"
baseurl: "" # does not include hostname

include: [".well-known"]

plugins_dir: [jekyll-paginate]
paginate: 5
paginate_path: "/news/:num/"

collections:
  minutes:
    output: true
    permalink: "/:collection/:path"

  pages:
    output: true
    permalink: /:path

  posts:
    output: true
    permalink: "/news/:categories/:year/:month/:day/:title.html"
    
defaults:
  - scope:
      type: minutes
    values:
      layout: minutes # minute page

  - scope:
      type: pages
    values:
      layout: page

  - scope:
      type: posts
    values:
      layout: post
